### ISSUE TITLE
导入文件时出现错误

### ISSUE THREAD

**Issue by seekerhuang** [kslz/sound_dataset_tools2#7]
Traceback (most recent call last):
  File "ui\mygui.py", line 366, in save_to_dataset
  File "utils\tools.py", line 364, in copy_file_to_workspace
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
请问出现这种情况是什么原因，完全按照视频导入的。

**Comment by seekerhuang** [comment]
使用的是带整合ffmpeg的0.5版本

**Comment by kslz** [comment]
看起来是导入的音频文件不对，能提供给我吗？

**Comment by kslz** [comment]
或者你自己用ffmpeg转换一下音频格式看看报什么错，把音频放到ffmpeg.exe目录下，然后在上方地址栏输入cmd启动命令行窗口，然后用下面这条命令看报错是什么
`ffmpeg -i input.mp3 output.wav`
input.mp3是你输入的音频文件

**Comment by 666lbwnb** [comment]
我也出现了这个错误

**Comment by kslz** [comment]
> 我也出现了这个错误

用我上面的方法试一下 这个问题应该是ffmpeg没能识别音频

**Comment by xwxYa** [comment]
> 

如果没能识别该怎么办呢？

**Comment by kslz** [comment]
> > 
> 
> 如果没能识别该怎么办呢？

ffmpeg都识别不了的基本就可以算作不是音频了，或者方便的话可以传上来我看下

**Comment by xwxYa** [comment]
> > > 
> > 
> > 
> > 如果没能识别该怎么办呢？
> 
> ffmpeg都识别不了的基本就可以算作不是音频了，或者方便的话可以传上来我看下

非常感谢您的回🙏🙏以及非常抱歉我当时似乎解决了，我也忘了出了什么问题( ﾟ∀。)
