### ISSUE TITLE
导入文件时点击确定没有反应

### ISSUE THREAD

**Issue by stolenradish** [kslz/sound_dataset_tools2#8]
![Snipaste_2023-05-23_10-22-06](https://github.com/kslz/sound_dataset_tools2/assets/134275719/791a76cf-721c-461a-85a8-6f1b42a26d9c)
这个项目有沟通群吗？或者其他的联系方式，我的邮箱zylf521525@163.com

**Comment by stolenradish** [comment]
2023-05-23 10:36:17,435 - guilogger - INFO - 数据集 kaishutest 添加成功
Traceback (most recent call last):
  File "ui\mygui.py", line 435, in save_to_dataset
  File "utils\tools.py", line 364, in copy_file_to_workspace
  File "ffmpeg\_run.py", line 313, in run
  File "ffmpeg\_run.py", line 284, in run_async
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1420, in _execute_child
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
